# Build stage
FROM node:21-slim AS build

WORKDIR /app

COPY package.json pnpm-lock.yaml /app/

RUN apt-get update \
    && apt-get install -y bash curl tesseract-ocr \
    && curl -1sLf 'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh' | bash \
    && apt-get install -y infisical \
    && npm i -g pnpm \
    && pnpm fetch \
    && pnpm install --frozen-lockfile --offline

# Runtime stage
FROM node:21-slim

WORKDIR /app

COPY --from=build /usr/bin/infisical /usr/bin/infisical
COPY --from=build Tesseract_* /usr/share/tesseract-ocr/5/tessdata
COPY --from=build /etc/ssl/certs /etc/ssl/certs

CMD ["npm", "run", "dev"]
ENTRYPOINT ["infisical", "run", "--env=dev", "--"]