version: '3.9'
services:
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - town-dev:/app/node_modules
    environment:
      - INFISICAL_TOKEN=${INFISICAL_TOKEN_DEV}
      - NODE_ENV=development
volumes:
  town-dev: