version: '3.9'
services:
  town-bot:
    container_name: town-bot
    restart: always
    image: ghcr.io/billyovo/town-bot:latest
    volumes:
      - tessdata:/app/dist/assets/tesseract
      - town-secrets:/app/dist/secrets/deposit
    depends_on:
      - secret-agent
    environment:
      - NODE_ENV=production
      - TZ=Asia/Taipei
  secret-agent:
    build:
      context: .
      dockerfile: secrets.Dockerfile
    container_name: secret-agent
    restart: always
    volumes:
      - town-secrets:/app/secrets/deposit

volumes:
  tessdata:
  town-secrets: