version: '3.9'
services:
  town-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: town-bot
    restart: always
    volumes:
      - tessdata:/app/dist/assets/tesseract
    env_file:
      - .env
    environment:
      - INFISICAL_TOKEN=${INFISICAL_TOKEN}
      - NODE_ENV=production
      - TZ=Asia/Taipei

volumes:
  tessdata: