version: '3.9'
services:
  town-bot-dev:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: town-bot-dev
    volumes:
      - .:/app
      - town-dev:/app/node_modules
    environment:
      - INFISICAL_TOKEN=${INFISICAL_TOKEN_DEV}
      - NODE_ENV=development
      - TZ=Asia/Taipei
volumes:
  town-dev: