version: '3.9'
services:
  town-bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - INFISICAL_TOKEN=${INFISICAL_TOKEN}
