infisical:
  address: "https://app.infisical.com"
auth:
  type: "universal-auth"
  config:
    client-id: "./secrets/client-id"
    client-secret: "./secrets/client-secret"
    remove_client_secret_on_read: false
sinks:
  - type: "file"
    config:
      path: "./secrets/deposit/access-token"
templates:
  - source-path: "./secrets/agent-template.yaml"
    destination-path: "./secrets/deposit/.env"
    config:
      polling-interval: 60s
      execute:
        timeout: 30