name: Build and Publish

on:
  registry_package: 
    types: [published, updated]
  workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: executing remote ssh commands using ssh key
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                port: ${{ secrets.SSH_PORT }}
                script: |
                  cd ${{ vars.SERVER_DIRECTORY }}
                  echo ${{ secrets.SSH_PASSWORD }} | sudo -S git pull origin master
                  echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker compose pull
                  echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker compose down
                  echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker compose up -d
            
            - name: Discord Notification
              env:
                DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
              uses: Ilshidur/action-discord@master
              with:
                args: '{{ EVENT_PAYLOAD.repository.full_name }} deploy finished'