name: Register
on:
  push:
    branches:
      - master
    paths:
      - 'src/commands/builders/*.ts'
  workflow_dispatch:
    
jobs:
  register:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '21.x'

      - name: Install dependencies
        run: npm install dotenv discord.js typescript ts-node

      - name: Run register
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
        run: npm run register
