name: Release Chain

on:
  push:
    branches: ["master"]
    paths:
      - "Dockerfile"
      - "docker-compose.yaml"
      - "src/**"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  build:
    permissions:
      id-token: write
      contents: read
      attestations: write
      packages: write
    secrets: inherit
    uses: ./.github/workflows/package.yml

  deploy:
    needs: build
    secrets: inherit
    uses: ./.github/workflows/deploy.yml

  register:
    needs: deploy
    secrets: inherit
    uses: ./.github/workflows/register.yml

  unregister:
    needs: register
    secrets: inherit
    uses: ./.github/workflows/unregister.yml
