name: Rebuild
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted]
    defaults:
      run:
        working-directory: ${{ vars.SERVER_DIRECTORY }}
    steps:
      - name: Pull Latest Code
        run: |
          git fetch origin master
          git reset --hard origin/master

      - name: Rebuild
        run: |
          docker compose up -d --build --remove-orphans

  notification:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "{{ EVENT_PAYLOAD.repository.full_name }} deploy finished!!"
